[package]
name = "brust"
version = "0.1.0"
authors = ["Sverre Johann Bjørke <sverrejb@gmail.com>"]
edition = "2018"

[dependencies]
strum = "0.15"
strum_macros = "0.15"
serde = "1.0.90"
serde_derive = "1.0.90"
yew = "0.6.0"